#!/bin/sh

remote="$1"
url="$2"

echo "Auto formatting code..."
if ! pyfmt --check; then
    echo
    echo "There are some code format issues!"
    echo "Please run 'pyfmt' and review before pushing."
    exit 1
fi

echo "Pushing to $remote ($url)"
